optimizer:
  params:
    weight_decay: 2.2434095538624117e-05
    lr: 2.6828093508423086e-05
model:
  encoder:
    params:
      hidden_size: 442
      num_layers: 3
      dropout: 0.0033911627666418256
  preprocess:
    params:
      time_process: cat
      num_norm: false
      cat_emb_dim: 128
      num_emb_dim: 16
  aggregation:
    name: ValidHiddenMean
