optimizer:
  params:
    weight_decay: 1.2903727070901565e-09
    lr: 0.00031609394669435977
model:
  preprocess:
    params:
      normalize_z: true
      num_norm: true
      cat_emb_dim: 48
      num_emb_dim: 96
      enc_num_layers: 3
      enc_aggregation: TakeLastHidden
      dec_hidden_size: 256
      dec_num_layers: 2
      dec_num_heads: 4
      dec_scale_hidden: 16
      contrastive_weight: 80.31230920850493
