optimizer:
  params:
    weight_decay: 1.966813198950528e-08
    lr: 0.00012720358922619596
model:
  preprocess:
    params:
      time_process: cat
      num_norm: false
      cat_emb_dim: 22
      num_emb_dim: 30
  encoder:
    params:
      hidden_size: 376
      pooling: ave
      dropout: 0.05381907759728454
      num_heads: 2
      embed_time: 104
pretrain_model:
  encoder:
    params:
      pooling: ave
pretrainer:
  total_iters: 100000
