optimizer:
  params:
    weight_decay: 9.897666393797422e-10
    lr: 0.03705032147208144
model:
  encoder:
    params:
      nhidden: 563
      embed_time: 79
  preprocess:
    params:
      time_process: cat
      num_norm: true
      cat_emb_dim: 2
      num_emb_dim: 6
