optimizer:
  params:
    weight_decay: 0.00019100604817668635
    lr: 4.355629862588497e-05
model:
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 6
      num_emb_dim: 9
  encoder:
    params:
      hidden_size: 360
      pooling: att
      dropout: 0.15752444057186263
      num_heads: 1
      embed_time: 120
pretrain_model:
  encoder:
    params:
      pooling: ave
pretrainer:
  total_iters: 0
