optimizer:
  params:
    weight_decay: 1.8922231013199282e-10
    lr: 0.0007719946571575053
model:
  encoder:
    params:
      emb_size: 56
      dropout: 0.11331561134301874
      num_heads: 2
  preprocess:
    params:
      time_process: cat
      num_norm: false
      cat_emb_dim: 17
      num_emb_dim: 33
