optimizer:
  params:
    weight_decay: 1.496222659036874e-10
    lr: 0.0015402696992453627
model:
  encoder:
    params:
      num_layers: 2
      scale_hidden: 3
      dropout: 0.028732967397732512
      pos_dropout: 0.2198209912379447
      pos_enc_type: base
      num_heads: 8
  preprocess:
    params:
      time_process: cat
      num_norm: true
      cat_emb_dim: 80
      num_emb_dim: 8
  aggregation:
    name: ValidHiddenMean
