optimizer:
  params:
    weight_decay: 7.282967231127358e-14
    lr: 0.001361193485901284
model:
  encoder:
    params:
      emb_size: 96
      dropout: 0.187651804356731
      num_heads: 8
  preprocess:
    params:
      time_process: cat
      num_norm: true
      cat_emb_dim: 17
      num_emb_dim: 25
