optimizer:
  params:
    weight_decay: 6.543317242395654e-05
    lr: 1.1027524250784924e-05
model:
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 31
      num_emb_dim: 13
  mtand_block:
    params:
      nhidden: 68
      embed_time: 96
      num_heads: 1
  encoder:
    params:
      num_layers: 3
      dropout: 0.12108127486924347
  aggregation:
    name: ValidHiddenMean
