optimizer:
  params:
    weight_decay: 0.00021192112208900967
    lr: 0.0001295813063475221
model:
  encoder:
    params:
      num_layers: 2
      scale_hidden: 14
      dropout: 0.2887511873649837
      pos_dropout: 0.08468760600129337
      pos_enc_type: cat
      num_heads: 8
  preprocess:
    params:
      time_process: cat
      num_norm: true
      cat_emb_dim: 112
      num_emb_dim: 128
  aggregation:
    name: ValidHiddenMean
