optimizer:
  params:
    weight_decay: 0.00041543891840427815
    lr: 0.0003462563803621598
model:
  preprocess:
    params:
      normalize_z: true
      num_norm: true
      cat_emb_dim: 72
      num_emb_dim: 56
      enc_num_layers: 2
      enc_aggregation: TakeLastHidden
      dec_hidden_size: 448
      dec_num_layers: 1
      dec_num_heads: 2
      dec_scale_hidden: 4
      contrastive_weight: 27.522159176011904
