optimizer:
  params:
    weight_decay: 1.9472483018564347e-05
    lr: 0.0006050064516198653
model:
  preprocess:
    params:
      time_process: cat
      num_norm: false
      cat_emb_dim: 20
      num_emb_dim: 2
  encoder:
    params:
      hidden_size: 128
      pooling: ave
      dropout: 0.31012086355711865
      num_heads: 4
      embed_time: 56
pretrain_model:
  encoder:
    params:
      pooling: ave
pretrainer:
  total_iters: 100000
