optimizer:
  params:
    weight_decay: 3.4475955575699536e-10
    lr: 0.0010011536488618148
model:
  encoder:
    params:
      hidden_size: 47
      pooling: bert
  preprocess:
    params:
      time_process: cat
      num_norm: true
      cat_emb_dim: 10
      num_emb_dim: 1
pretrain_model:
  encoder:
    params:
      pooling: ave
pretrainer:
  total_iters: 100000
