optimizer:
  params:
    weight_decay: 7.233404168725049e-07
    lr: 0.047379338536260446
model:
  encoder:
    params:
      nhidden: 271
      embed_time: 76
  preprocess:
    params:
      time_process: cat
      num_norm: false
      cat_emb_dim: 5
      num_emb_dim: 9
