optimizer:
  params:
    weight_decay: 2.652377366486337e-10
    lr: 0.0008336673823589733
model:
  encoder:
    params:
      n_layer: 3
      rescale_prenorm_residual: true
  preprocess:
    params:
      time_process: cat
      num_norm: false
      cat_emb_dim: 85
      num_emb_dim: 58
  aggregation:
    name: ValidHiddenMean
