optimizer:
  params:
    weight_decay: 2.84310393361831e-13
    lr: 1.548454089552597e-05
model:
  encoder:
    params:
      hidden_size: 89
      num_layers: 3
      dropout: 1.3345186719277086e-10
  preprocess:
    params:
      time_process: none
      num_norm: true
      cat_emb_dim: 11
      num_emb_dim: 42
  aggregation:
    name: TakeLastHidden
