optimizer:
  params:
    weight_decay: 1.0022089847475298e-06
    lr: 0.0006036405141552167
model:
  preprocess:
    params:
      time_process: cat
      num_norm: false
      cat_emb_dim: 20
      num_emb_dim: 1
  mtand_block:
    params:
      nhidden: 403
      embed_time: 128
      num_heads: 1
  encoder:
    params:
      num_layers: 1
      dropout: 0.247062778747564
  aggregation:
    name: TakeLastHidden
