optimizer:
  params:
    weight_decay: 3.307381473194515e-09
    lr: 4.500102556454455e-05
model:
  preprocess:
    params:
      normalize_z: true
      num_norm: false
      cat_emb_dim: 64
      num_emb_dim: 56
      enc_num_layers: 3
      enc_aggregation: TakeLastHidden
      dec_hidden_size: 288
      dec_num_layers: 3
      dec_num_heads: 1
      dec_scale_hidden: 8
      contrastive_weight: 80.45253425663151
