optimizer:
  params:
    weight_decay: 1.4648229166807348e-08
    lr: 0.020326848812375127
model:
  encoder:
    params:
      n_layer: 1
      rescale_prenorm_residual: false
  preprocess:
    params:
      time_process: none
      num_norm: true
      cat_emb_dim: 59
      num_emb_dim: 100
  aggregation:
    name: TakeLastHidden
