optimizer:
  params:
    weight_decay: 7.252078554810376e-11
    lr: 1.4546290507385743e-05
model:
  encoder:
    params:
      n_layer: 1
      rescale_prenorm_residual: true
  preprocess:
    params:
      time_process: none
      num_norm: true
      cat_emb_dim: 8
      num_emb_dim: 77
  aggregation:
    name: ValidHiddenMean
