optimizer:
  params:
    weight_decay: 0.00019256055643854467
    lr: 0.0002016146142063395
model:
  preprocess:
    params:
      normalize_z: true
      num_norm: true
      cat_emb_dim: 48
      num_emb_dim: 8
      enc_num_layers: 2
      enc_aggregation: TakeLastHidden
      dec_hidden_size: 224
      dec_num_layers: 3
      dec_num_heads: 4
      dec_scale_hidden: 10
      contrastive_weight: 67.84091746080215
