optimizer:
  params:
    weight_decay: 2.3944293387632036e-06
    lr: 9.095646534564997e-05
model:
  preprocess:
    params:
      normalize_z: false
      num_norm: false
      cat_emb_dim: 128
      num_emb_dim: 88
      enc_num_layers: 3
      enc_aggregation: TakeLastHidden
      dec_hidden_size: 224
      dec_num_layers: 2
      dec_num_heads: 4
      dec_scale_hidden: 14
      contrastive_weight: 27.422871385594803
