optimizer:
  params:
    weight_decay: 4.5287303928079784e-07
    lr: 0.00543517858629937
model:
  encoder:
    params:
      n_layer: 2
      rescale_prenorm_residual: false
  preprocess:
    params:
      time_process: cat
      num_norm: true
      cat_emb_dim: 104
      num_emb_dim: 68
  aggregation:
    name: TakeLastHidden
