optimizer:
  params:
    weight_decay: 2.386859490280754e-07
    lr: 3.1096139986052354e-05
model:
  preprocess:
    params:
      normalize_z: false
      num_norm: false
      cat_emb_dim: 48
      num_emb_dim: 120
      enc_num_layers: 3
      enc_aggregation: ValidHiddenMean
      dec_hidden_size: 160
      dec_num_layers: 2
      dec_num_heads: 4
      dec_scale_hidden: 7
      contrastive_weight: 79.67034556425804
