optimizer:
  params:
    weight_decay: 3.748656864666613e-15  # 30%, less is better
    lr: 0.00028933514655100125  # 100% [8e-5, 8e-4]
model:
  encoder:
    params:
      nhidden: 346  # 100%, [200, 400]
      embed_time: 89  # 30% [80, 112]
  preprocess:
    params:
      time_process: cat  # 100%
      num_norm: false  # 100%
      cat_emb_dim: 6  # ???
      num_emb_dim: 2  # ???
