optimizer:
  params:
    weight_decay: 4.804781159905981e-09
    lr: 0.0050792737109190845
model:
  encoder:
    params:
      nhidden: 525
      embed_time: 126
  preprocess:
    params:
      time_process: cat
      num_norm: false
      cat_emb_dim: 3
      num_emb_dim: 7
