optimizer:
  params:
    weight_decay: 2.9553163629156415e-14
    lr: 0.0009703077234720955
model:
  head_0:
    params:
      out_features: 1081
  drop_0:
    params:
      p: 7.451385557848652e-10
  preprocess:
    params:
      time_process: cat
      num_norm: true
      cat_emb_dim: 117
      num_emb_dim: 118
  aggregation:
    name: ValidHiddenMean
