optimizer:
  params:
    weight_decay: 9.330259089796469e-06
    lr: 1.0347316115983885e-05
model:
  preprocess:
    params:
      time_process: diff
      num_norm: false
      cat_emb_dim: 19
      num_emb_dim: 2
  encoder:
    params:
      hidden_size: 400
      pooling: att
      dropout: 0.20269340391954438
      num_heads: 8
      embed_time: 112
pretrain_model:
  encoder:
    params:
      pooling: ave
pretrainer:
  total_iters: 100000
