optimizer:
  params:
    weight_decay: 2.964322009851163e-07
    lr: 1.2863457127990751e-05
model:
  encoder:
    params:
      emb_size: 96
      dropout: 0.14212403744250657
      num_heads: 2
  preprocess:
    params:
      time_process: cat
      num_norm: true
      cat_emb_dim: 57
      num_emb_dim: 9
