optimizer:
  params:
    weight_decay: 1.4980169378784764e-07
    lr: 5.0959637317021976e-05
model:
  encoder:
    params:
      hidden_size: 531
      num_layers: 2
      dropout: 1.5298375336712876e-09
  preprocess:
    params:
      time_process: cat
      num_norm: true
      cat_emb_dim: 117
      num_emb_dim: 80
  aggregation:
    name: TakeLastHidden
unsupervised_loss:
  params:
    margin: 0.6027037244515981
unsupervised_trainer:
  total_iters: 100000
