optimizer:
  params:
    weight_decay: 1.0588050876555269e-07
    lr: 1.3845073443604668e-05
model:
  preprocess:
    params:
      time_process: cat
      num_norm: true
      cat_emb_dim: 20
      num_emb_dim: 16
  encoder:
    params:
      hidden_size: 72
      pooling: ave
      dropout: 0.14991236547176678
      num_heads: 2
      embed_time: 64
pretrain_model:
  encoder:
    params:
      pooling: ave
pretrainer:
  total_iters: 0
