optimizer:
  params:
    weight_decay: 5.8541044100148254e-09  # 0%
    lr: 0.020376852273722393  # 30%, [2e-4, 3e-2]
model:
  head_0:
    params:
      out_features: 574  # 3% [16, 1000]
  drop_0:
    params:
      p: 0.02492837655510699  # 3% [0, 0.3]
  preprocess:
    params:
      time_process: cat  # 10%, {cat, diff}
      num_norm: true  # 100%, true
      cat_emb_dim: 121  # 10% [40, 128]
      num_emb_dim: 83  # 30% [1, 83]
  aggregation:
    name: ValidHiddenMean  # 100%
