optimizer:
  params:
    weight_decay: 1.402917078051288e-09
    lr: 0.009258000785369409
model:
  encoder:
    params:
      hidden_size: 106
      pooling: att
  preprocess:
    params:
      time_process: none
      num_norm: true
      cat_emb_dim: 7
      num_emb_dim: 2
pretrain_model:
  encoder:
    params:
      pooling: ave
pretrainer:
  total_iters: 0
