optimizer:
  params:
    weight_decay: 3.5219198071192443e-14
    lr: 0.0023246862475988254
model:
  preprocess:
    params:
      time_process: cat
      num_norm: false
      cat_emb_dim: 24
      num_emb_dim: 16
  mtand_block:
    params:
      nhidden: 147
      embed_time: 80
      num_heads: 1
  encoder:
    params:
      num_layers: 1
      dropout: 0.2719681805419086
  aggregation:
    name: TakeLastHidden
