optimizer:
  params:
    weight_decay: 8.195782363051053e-06
    lr: 0.00025624346035212054
model:
  encoder:
    params:
      num_layers: 3
      scale_hidden: 6
      dropout: 0.13903527621230427
      pos_dropout: 0.2992075780281245
      pos_enc_type: cat
      num_heads: 4
  preprocess:
    params:
      time_process: cat
      num_norm: true
      cat_emb_dim: 16
      num_emb_dim: 128
  aggregation:
    name: ValidHiddenMean
