optimizer:
  params:
    weight_decay: 0.0010292503033565573
    lr: 3.849397027192484e-05
model:
  preprocess:
    params:
      normalize_z: false
      num_norm: true
      cat_emb_dim: 96
      num_emb_dim: 72
      enc_num_layers: 1
      enc_aggregation: TakeLastHidden
      dec_hidden_size: 416
      dec_num_layers: 3
      dec_num_heads: 2
      dec_scale_hidden: 8
      contrastive_weight: 94.05710501987843
