log_dir: log/bpi_17
patience: 5
n_classes: 2
main_metric: MulticlassAUROC
main_loss: 
  name: nn.CrossEntropyLoss

cc: 
  Action: 6
  org_resource: 149
  concept_name: 21
  EventOrigin: 4
  lifecycle_transition: 8
  case_LoanGoal: 15
  case_ApplicationType: 3
nn:
  - case_RequestedAmount
  - FirstWithdrawalAmount
  - NumberOfTerms
  - MonthlyCost
  - CreditScore
  - OfferedAmount

data:
  dataset:
    parquet_path: "data/bpi_17/preprocessed/train"
    random_split: true
    split_seed: 42

    split_sizes: 
      - 0.7   # train
      - 0.15  # train_val
      - 0.15  # hpo_val

  preprocessing:
    common_pipeline: &common_pipeline
      max_seq_len: 140
      time_name: time_timestamp
      index_name: OfferID
      target_name: Accepted
      cat_cardinalities: ${cc}
      num_names: ${nn}
      batch_transforms:
        - DatetimeToFloat:
            loc: "2016-01-01"
            scale: [365, "D"]
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - Logarithm:
            names: ["case_RequestedAmount", "FirstWithdrawalAmount", "OfferedAmount"]
        - MaskValid
        - FillNans:
            fill_value: -1.0
    contrastive_pipeline:
      <<: *common_pipeline
      batch_transforms:
        - DatetimeToFloat:
            loc: "2016-01-01"
            scale: [365, "D"]
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - Logarithm:
            names: ["case_RequestedAmount", "FirstWithdrawalAmount", "OfferedAmount"]
        - MaskValid
        - FillNans:
            fill_value: -1.0
        - ContrastiveTarget
        - RandomSlices:
            split_count: 5
            cnt_min: 4
            cnt_max: 10
            short_seq_crop_rate: 0.8
            seed: 0
    primenet_pipeline:
      <<: *common_pipeline
      batch_transforms:
        - DatetimeToFloat:
            loc: "2016-01-01"
            scale: [365, "D"]
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - Logarithm:
            names: ["case_RequestedAmount", "FirstWithdrawalAmount", "OfferedAmount"]
        - MaskValid
        - FillNans:
            fill_value: -1.0
        - PrimeNetSampler:
            segment_num: 3

  loaders:
    train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      drop_incomplete: true
      shuffle: true
      loop: false
      num_workers: 4
      random_seed: 42
    full_train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    train_val:
      split_idx: 1
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    hpo_val:
      split_idx: 2
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4

test_data:
  dataset:
    parquet_path: "data/bpi_17/preprocessed/test"
    split_sizes: 
      - 1.0
  preprocessing:
    common_pipeline: *common_pipeline
  loaders:
    test:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4

metrics:
  - name: ${main_metric}
    params: 
      num_classes: ${n_classes}
