log_dir: log/electric_devices
patience: 5
n_classes: 7
main_metric: MulticlassAccuracy
main_loss: 
  name: nn.CrossEntropyLoss

cc: 
nn:
  - dim_0

data:
  dataset:
    parquet_path: "data/electric_devices/preprocessed/train"
    random_split: true
    split_seed: 42

    split_sizes: 
      - 0.7   # train
      - 0.15  # train_val
      - 0.15  # hpo_val

  preprocessing:
    common_pipeline: &common_pipeline
      max_seq_len: 96
      time_name: time
      index_name: index
      target_name: class_vals
      cat_cardinalities: ${cc}
      num_names: ${nn}
      batch_transforms:
        - RescaleTime:
            loc: 0.0
            scale: 96.0
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - TargetToLong
        - MaskValid
    contrastive_pipeline:
      <<: *common_pipeline
      batch_transforms:
        - RescaleTime:
            loc: 0.0
            scale: 96.0
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - MaskValid
        - ContrastiveTarget
        - RandomSlices:
            split_count: 5
            cnt_min: 10
            cnt_max: 50
            short_seq_crop_rate: 0.8
            seed: 0
    primenet_pipeline:
      <<: *common_pipeline
      batch_transforms:
        - RescaleTime:
            loc: 0.0
            scale: 96.0
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - TargetToLong
        - MaskValid
        - PrimeNetSampler:
            segment_num: 3

  loaders:
    train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      drop_incomplete: true
      shuffle: true
      loop: false
      num_workers: 4
      random_seed: 42
    full_train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    train_val:
      split_idx: 1
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    hpo_val:
      split_idx: 2
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4

test_data:
  dataset:
    parquet_path: "data/electric_devices/preprocessed/test"
    split_sizes: 
      - 1.0
  preprocessing:
    common_pipeline: *common_pipeline
  loaders:
    test:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4

metrics:
  - name: ${main_metric}
    params: 
      num_classes: ${n_classes}
