log_dir: log/taobao
patience: 10
n_classes: 2
main_metric: MulticlassAUROC
main_loss: 
  name: nn.CrossEntropyLoss

cc: 
  behavior_type: 5
  item_id: 1904
nn:

data:
  dataset:
    parquet_path: "data/taobao/preprocessed/train"
    random_split: true
    split_seed: 42

    split_sizes: 
      - 0.7   # train
      - 0.15  # train_val
      - 0.15  # hpo_val

  preprocessing:
    common_pipeline: &common_pipeline
      max_seq_len: 1000
      time_name: time
      index_name: user_id
      target_name: payment_next_7d
      cat_cardinalities: ${cc}
      batch_transforms:
        - DatetimeToFloat:
            loc: "2014-11-18"
            scale: [30, "D"]
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - MaskValid
    contrastive_pipeline:
      <<: *common_pipeline
      batch_transforms:
        - DatetimeToFloat:
            loc: "2014-11-18"
            scale: [30, "D"]
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - MaskValid
        - ContrastiveTarget
        - RandomSlices:
            split_count: 5
            cnt_min: 25
            cnt_max: 200
            short_seq_crop_rate: 0.8
            seed: 0
    primenet_pipeline:
      <<: *common_pipeline
      batch_transforms:
        - DatetimeToFloat:
            loc: "2014-11-18"
            scale: [30, "D"]
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - MaskValid
        - PrimeNetSampler:
            segment_num: 3

  loaders:
    train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      drop_incomplete: true
      shuffle: true
      loop: false
      num_workers: 4
      random_seed: 42
    full_train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    train_val:
      split_idx: 1
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    hpo_val:
      split_idx: 2
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4

test_data:
  dataset:
    parquet_path: "data/taobao/preprocessed/test"
    split_sizes: 
      - 1.0
  preprocessing:
    common_pipeline: *common_pipeline
  loaders:
    test:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4

metrics:
  - name: ${main_metric}
    params: 
      num_classes: ${n_classes}
